language: r
cache: packages
sudo: required

before_script:
  - Rscript -e "if (!require('covr')) install.packages('covr')"

matrix:
  include:
    - r: release
    - r: oldrel
    - r: devel
    - os: osx
    - os: linux
  allow_failures:
    - os: osx

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
