language: r
sudo: required

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - CRAN=http://cran.rstudio.com

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2 ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C / ; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install r-cran-devtools r-cran-testthat; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'library(devtools); library(methods); options(repos=c(CRAN="http://cran.rstudio.com")); devtools::install_github("jimhester/covr", build_vignettes = FALSE)'; fi

r_binary_packages:
  - numDeriv
  - plyr
  - magrittr
  - testthat

after_failure:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /home/travis/build/ChingChuan-Chen/milr/milr.Rcheck/00install.out; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cat /Users/travis/build/ChingChuan-Chen/milr/milr.Rcheck/00install.out; fi

after_success:
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov();covr::coveralls()'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /home/travis/build/ChingChuan-Chen/milr/milr.Rcheck/00install.out; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cat /Users/travis/build/ChingChuan-Chen/milr/milr.Rcheck/00check.log; fi

notifications:
  email:
    on_success: none
    on_failure: none
