language: R
cache: packages
latex: true
     
warnings_are_errors: false
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual --as-cran

before_script:
  - Rscript -e "if (!require('covr')) install.packages('covr')"

matrix:
  include:
    - r: release
    - r: oldrel
    - r: devel
    - os: osx
    - os: linux
  allow_failures:
    - os: osx

addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - gcc-6
     - g++-6
     - gfortran-6
     
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 100; fi
  - g++ --version
  - gfortran --version

script: 
  - |
    travis_wait 40 R CMD build .
    travis_wait 40 R CMD check --no--vignettes --no-manual --as-cran milr*tar.gz

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
